apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-operators
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-ai-operator
          path: components/operators/openshift-ai/aggregate/overlays/stable-2.19-serving-only
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-serverless-operator
          path: components/operators/openshift-serverless/operator/overlays/stable
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-servicemesh-operator
          path: components/operators/openshift-servicemesh/operator/overlays/stable
  template:
    spec:
      source:
        targetRevision: main