kind: DataScienceCluster
apiVersion: datasciencecluster.opendatahub.io/v1
metadata:
  name: default
spec:
  components:
    #single-model serving
    kserve:
      managementState: Managed
      defaultDeploymentMode: Serverless
      RawDeploymentServiceConfig: Headed
      serving:
        managementState: Managed
        name: knative-serving
        ingressGateway:
          certificate:
            secretName: knative-serving-cert 
            type: OpenshiftDefaultIngress
    #multi-model serving
    modelmeshserving:
      managementState: Managed