apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config-app-of-apps
  namespace: openshift-gitops
  labels:
    gitops.ownedBy: default
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: patch-me-see-overlays
    repoURL: https://github.com/edwin-noh/rhoai.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true