apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-operators
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-ai-operator
          path: components/operators/openshift-ai/aggregate/overlays/eus-2.16-nvidia-gpu